@host = localhost
@port = 3000
@user = user
// user login
POST http://{{host}}:{{port}}/{{user}}/login HTTP/1.1
content-type: application/json

{
    "user":"Stephen Ye",
    "password": "Yekang-2019"
}

###
GET http://{{host}}:{{port}}/{{user}}/modules HTTP/1.1
content-type: application/json

###
GET http://{{host}}:{{port}}/{{user}}/articles/1 HTTP/1.1
content-type: application/json

###
GET http://{{host}}:{{port}}/{{user}}/articles/info/3 HTTP/1.1
content-type: application/json